# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amostra',
            old_name='title',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='amostra',
            old_name='created_date',
            new_name='Data',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='author',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='text',
        ),
        migrations.AddField(
            model_name='amostra',
            name='Amostras',
            field=models.CharField(choices=[(b'A', b'MACRO'), (b'I', b'MICRO'), (b'F', b'FISICA')], default=b'NAO SELECIONADO', max_length=1),
        ),
    ]
