# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0002_auto_20161024_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='Cod_Amostra',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Gleba',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Municipio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Propriedade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Valor',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
