# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0003_auto_20161116_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='Cod_Amostra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Gleba',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Propriedade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
