# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0004_auto_20161214_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='Valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
