# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0005_auto_20161214_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='Amostras',
            field=models.CharField(choices=[(b'MACRO', b' MACRONUTRIENTES (ROTINA)'), (b'MICRONUTRIENTES', b'MICRONUTRIENTES (S, B, Fe, Cu, Mn, Zn)'), (b'MICRO', b'MICRO (Fe, Cu, Mn, Zn)'), (b'FISICA', b'ANALISE GRANULOMETRICA (FISICA)'), (b'MICRO+MICRO', b'MACRO+MICRO (Fe, Cu, Mn, Zn)'), (b'MICRO+MICRONUTRIENTES', b'MACRO+MICRONUTRIENTES (S, B, Fe, Cu, Mn, Zn)'), (b'MACRO+MICRO+GRAN', b'MACRO+MICRO+GRANULOMETRICA(FISICA)'), (b'ELEMENTOI', b'ELEMENTO ISOLADO (S, B)'), (b'RECOMENDACOES', b'RECOMENDACOES'), (b'TECIDO', b'ANALISE DE TECIDO VEGETAL (COMPLETA)'), (b'PH', b'pH ISOLADO (H2O , CaCl2)')], default=b'NAO SELECIONADO', max_length=20),
        ),
    ]
