# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0007_gastos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gastos',
            new_name='Gasto',
        ),
    ]
