# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0008_auto_20170110_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='Valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='Valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
