# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0010_auto_20170112_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
