# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0011_amostra_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_Pagos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Amostras',
            field=models.CharField(choices=[(b'MACRO', b' MACRONUTRIENTES (ROTINA)'), (b'MICRONUTRIENTES', b'MICRONUTRIENTES (S, B, Fe, Cu, Mn, Zn)'), (b'FISICA', b'ANALISE GRANULOMETRICA (FISICA)'), (b'MICRO+MICRONUTRIENTES', b'MACRO+MICRONUTRIENTES (S, B, Fe, Cu, Mn, Zn)'), (b'MACRO+MICRO+GRAN', b'MACRO+MICRO+GRANULOMETRICA(FISICA)'), (b'ELEMENTOI', b'ELEMENTO ISOLADO (S, B)'), (b'TECIDO', b'ANALISE DE TECIDO VEGETAL (COMPLETA)'), (b'PH', b'pH ISOLADO (H2O , CaCl2)')], default=b'NAO SELECIONADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='amostra',
            name='total',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='livrocaixa.Total'),
            preserve_default=False,
        ),
    ]
