# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0012_auto_20170116_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='total',
        ),
        migrations.DeleteModel(
            name='Total',
        ),
    ]
