# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0013_auto_20170116_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrocaixa.Amostra')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrocaixa.Gasto')),
            ],
        ),
    ]
