# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livrocaixa', '0014_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='amostra',
        ),
        migrations.RemoveField(
            model_name='total',
            name='gasto',
        ),
        migrations.AddField(
            model_name='gasto',
            name='Data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Total',
        ),
    ]
